ALTER TABLE "Review" ADD COLUMN "strengths" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Review" ADD COLUMN "improvements" TEXT NOT NULL DEFAULT '';
ALTER TABLE "Review" ADD COLUMN "resources" TEXT;
ALTER TABLE "Review" ALTER COLUMN "strengths" DROP DEFAULT;
ALTER TABLE "Review" ALTER COLUMN "improvements" DROP DEFAULT;